### ISSUE TITLE
Arc A770 MiniCPM-o-2_6 performance issue

### ISSUE THREAD

**Issue by caijimin** [intel/ipex-llm#12937]
I'm evaluating multimodal image/video understanding on A770. Had tested `MimiCPM-o-2_6/MiniCPU-V-2_6/Janus-Pro-7B/Qwen2-VL-7B-Instruct` on A770, environment variable **SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS** has big performance impact, and it's also related to different task.

```
source /opt/intel/oneapi/setvars.sh
export USE_XETLA=OFF
export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1
export SYCL_CACHE_PERSISTENT=1
```  
For image chat task, the image is http://farm6.staticflickr.com/5268/5602445367_3504763978_z.jpg in ipex-llm example.
```
ipex-llm/python/llm/example/GPU/HuggingFace/Multimodal/MiniCPM-o-2_6# python chat.py --repo-id-or-model-path /models/MiniCPM-o-2_6/ --image-path 5602445367_3504763978_z.jpg --prompt "请详细描述图像内容" --n-predict 512

Inference time: 10.233431100845337 s
```
After `export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0` the result is `Inference time: 3.5721495151519775 s`.  Seems for image understanding, should unset SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS.

But when I test video understanding task (see below video_chat.py)
```python
 import os
import time
import torch
import librosa
import argparse
from PIL import Image
from transformers import AutoTokenizer
from ipex_llm.transformers import AutoModel
from decord import VideoReader, cpu    # pip install decord

MAX_NUM_FRAMES=10 # if cuda OOM set a smaller number

def encode_video(video_path):
    def uniform_sample(l, n):
        gap = len(l) / n
        idxs = [int(i * gap + gap / 2) for i in range(n)]
        return [l[i] for i in idxs]

    #vr = VideoReader(video_path, ctx=cpu(0), width=960, height=540)
    vr = VideoReader(video_path, ctx=cpu(0))
    sample_fps = round(vr.get_avg_fps() / 1)  # FPS
    frame_idx = [i for i in range(0, len(vr), sample_fps)]
    print(frame_idx)
    if len(frame_idx) > MAX_NUM_FRAMES:
        frame_idx = uniform_sample(frame_idx, MAX_NUM_FRAMES)
    frames = vr.get_batch(frame_idx).asnumpy()
    frames = [Image.fromarray(v.astype('uint8')) for v in frames]
    print('num frames:', len(frames))
    return frames

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Chat with MiniCPM-o-2_6 with text/audio/image')
    parser.add_argument('--repo-id-or-model-path', type=str, default="openbmb/MiniCPM-o-2_6",
                        help='The Hugging Face or ModelScope repo id for the MiniCPM-o-2_6 model to be downloaded'
                             ', or the path to the checkpoint folder')
    parser.add_argument('--video-path', type=str,
                        help='The path to the image for inference.')
    parser.add_argument('--audio-path', type=str,
                        help='The path to the audio for inference.')
    parser.add_argument('--prompt', type=str,
                        help='Prompt for inference.')
    parser.add_argument('--n-predict', type=int, default=32,
                        help='Max tokens to predict')
    
    args = parser.parse_args()

    model_path = args.repo_id_or_model_path
    video_path = args.video_path
    audio_path = args.audio_path

    modules_to_not_convert = []
    init_vision = False
    init_audio = False
    if video_path is not None and os.path.exists(video_path):
        init_vision = True
        modules_to_not_convert += ["vpm", "resampler"]
    if audio_path is not None and os.path.exists(audio_path):
        init_audio = True
        modules_to_not_convert += ["apm"]

    # Load model in 4 bit,
    # which convert the relevant layers in the model into INT4 format
    model = AutoModel.from_pretrained(model_path, 
                                      load_in_low_bit="sym_int4",
                                      optimize_model=True,
                                      trust_remote_code=True,
                                      attn_implementation='sdpa',
                                      use_cache=True,
                                      init_vision=init_vision,
                                      init_audio=init_audio,
                                      init_tts=False,
                                      modules_to_not_convert=modules_to_not_convert)
    
    model = model.half().to('xpu')

    tokenizer = AutoTokenizer.from_pretrained(model_path,
                                              trust_remote_code=True)
    

    # The following code for generation is adapted from 
    # https://huggingface.co/openbmb/MiniCPM-o-2_6#addressing-various-audio-understanding-tasks and
    # https://huggingface.co/openbmb/MiniCPM-o-2_6#chat-with-single-image
    content = []
    if init_vision:
        frames = encode_video(video_path)
    if args.prompt is not None:
        content.append(args.prompt)
    if init_audio:
        audio_input, _ = librosa.load(audio_path, sr=16000, mono=True)
        content.append(audio_input)
    messages = [{'role': 'user', 'content': frames + [args.prompt]}]


    with torch.inference_mode():
        # ipex_llm model needs a warmup, then inference time can be accurate
        model.chat(
            msgs=messages,
            tokenizer=tokenizer,
            sampling=True,
            max_new_tokens=args.n_predict,
        )

        st = time.time()
        response = model.chat(
            msgs=messages,
            tokenizer=tokenizer,
            sampling=True,
            max_new_tokens=args.n_predict,
        )
        torch.xpu.synchronize()
        end = time.time()

    output_ids = tokenizer.encode(response, return_tensors="pt").to('xpu')
    print(f'Output lengh: {len(output_ids[0])}')

    print(f'Inference time: {end-st} s')
    print('-'*20, 'Input Video Path', '-'*20)
    print(video_path)
    print('-'*20, 'Input Audio Path', '-'*20)
    print(audio_path)
    print('-'*20, 'Input Prompt', '-'*20)
    print(args.prompt)
    print('-'*20, 'Chat Output', '-'*20)
    print(response)
```
```
python video_chat.py --repo-id-or-model-path /models/MiniCPM-o-2_6/ --video-path Skiing-1080p.mp4 --prompt "请描述这个视频,使用中文" --n-predict 512

export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0
Inference time: 105.26203894615173 s

export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1
Inference time: 16.64881181716919 s
```
`Skiing-1080p.mp4`'s resolution is 1920x1080, it's transcoded from original 960x540 `https://huggingface.co/openbmb/MiniCPM-o-2_6/blob/main/assets/Skiing.mp4`
`ffmpeg -i Skiing.mp4 -c:v h264 -s 1920x1080 Skiing-1080p.mp4`

Using original Skiing.mp4
```
export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0
Inference time: 6.2952880859375 s

export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1
Inference time: 12.700184106826782 s
```
Seems it's also related to resolution. It's difficult to choose **SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS** value.

**Comment by ATMxsp01** [comment]
We are trying to reproduce your issue, and will inform you if there are any updates.

**Comment by ATMxsp01** [comment]
After trying, we did not reproduce the long time cost in `video_chat.py`  `Skiing-1080p.mp4` with `SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0`.

Could you retry your test to make sure the previous result is not an outlier?

**Comment by caijimin** [comment]
I upgraded the kernel to 6.5.0-35-generic and also upgraded package "intel-i915-dkms intel-fw-gpu", this issue is disappeared, seems it's driver version problem. Thanks.
