### ISSUE TITLE
flash-moe  for deepseek portable zip, crash as Illegal instruction.

### ISSUE THREAD

**Issue by ParallelDqn** [intel/ipex-llm#12959]
**Describe the bug**
flash-moe  for deepseek portable zip, crash as Illegal instruction.

**How to reproduce**
run flash-moe with deepseek q4

**Screenshots**
Found 1 SYCL devices:
|  |                   |                                       |       |Max    |        |Max  |Global |                     |
|  |                   |                                       |       |compute|Max work|sub  |mem    |                     |
|ID|        Device Type|                                   Name|Version|units  |group   |group|size   |       Driver version|
|--|-------------------|---------------------------------------|-------|-------|--------|-----|-------|---------------------|
| 0| [level_zero:gpu:0]|                Intel Graphics [0xe20b]|   20.1|    160|    1024|   32| 12168M|         1.6.32224+14|
llama_kv_cache_init:        CPU KV buffer size =  4240.00 MiB
llama_kv_cache_init:      SYCL0 KV buffer size =   640.00 MiB
llama_new_context_with_model: KV self size  = 4880.00 MiB, K (f16): 2928.00 MiB, V (f16): 1952.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.49 MiB
llama_new_context_with_model:      SYCL0 compute buffer size =   852.00 MiB
llama_new_context_with_model:  SYCL_Host compute buffer size =   774.01 MiB
llama_new_context_with_model: graph nodes  = 5489 (with bs=1024), 5025 (with bs=1)
llama_new_context_with_model: graph splits = 756 (with bs=1024), 19 (with bs=1)
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
./flash-moe: line 7: 14534 Illegal instruction

**Environment information**
from env_check.sh
-----------------------------------------------------------------
PYTHON_VERSION=3.12.9
-----------------------------------------------------------------
Transformers is not installed. 
-----------------------------------------------------------------
PyTorch is not installed. 
-----------------------------------------------------------------
ipex-llm WARNING: Package(s) not found: ipex-llm
-----------------------------------------------------------------
IPEX is not installed. 
-----------------------------------------------------------------
CPU Information: 
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        43 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               64
On-line CPU(s) list:                  0-63
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen Threadripper 3970X 32-Core Processor
CPU family:                           23
Model:                                49
Thread(s) per core:                   2
Core(s) per socket:                   32
Socket(s):                            1
Stepping:                             0
Frequency boost:                      enabled
CPU(s) scaling MHz:                   22%
CPU max MHz:                          4550.0000
-----------------------------------------------------------------
Total CPU Memory: 251.555 GB
Memory Type: DDR4 
-----------------------------------------------------------------
Operating System: 
Ubuntu 24.04.2 LTS \n \l

-----------------------------------------------------------------
Linux ai 6.11.0-19-generic #19~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 17 11:51:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------
./check.sh: line 148: xpu-smi: command not found
-----------------------------------------------------------------
  Driver Version                                  2024.18.12.0.05_160000
  Driver UUID                                     32342e35-322e-3332-3232-340000000000
  Driver Version                                  24.52.32224
-----------------------------------------------------------------
Driver related package version:
-----------------------------------------------------------------
./check.sh: line 167: sycl-ls: command not found
igpu not detected
-----------------------------------------------------------------
xpu-smi is not installed. Please install xpu-smi according to README.md

**Additional context**
from sycl-ls:
[level_zero:gpu][level_zero:0] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Graphics [0xe20b] 20.1.0 [1.6.32224+14]
[opencl:cpu][opencl:0] Intel(R) OpenCL, AMD Ryzen Threadripper 3970X 32-Core Processor  OpenCL 3.0 (Build 0) [2024.18.12.0.05_160000]
[opencl:gpu][opencl:1] Intel(R) OpenCL Graphics, Intel(R) Graphics [0xe20b] OpenCL 3.0 NEO  [24.52.32224]

So it seems a local build is best way to solve this issue.     any info for how to build flash-moe from source ?

**Comment by ParallelDqn** [comment]
I tried  flash-moe from another machine which is intel i7 12700K and it works there.  
When compare the IS diff from 12700k to Threadripper, the answer is   avx_vnni,   which make sense here as it's intel project.

But if anybody can help show me a light where is the code and I can still build it for more compatibility,  thanks alot.

**Comment by qiuxin2012** [comment]
Yes, lacking of avx_vnni will get `Ollegal instruction` error. We are removing this requirement.
