### ISSUE TITLE
Tensor parallel vllm fails on eGPU

### ISSUE THREAD

**Issue by kirel** [intel/ipex-llm#13131]
**Describe the bug**
When I try to run the vLLM container https://github.com/intel/ipex-llm/blob/main/docs/mddocs/DockerGuides/vllm_docker_quickstart.md with `tensor_parallel_size=2` on my 2 A770 system where the second A770 is connected to the m2 slot of mainboard I get

```
> dmesg
[ 1470.497571] i915 0000:07:00.0: [drm] GPU HANG: ecode 12:10:85def5fa, in ray::WrapperWit [14631]
[ 1470.497577] i915 0000:07:00.0: [drm] ray::IDLE[14631] context reset due to GPU hang
[ 1470.612921] i915 0000:03:00.0: [drm] GPU HANG: ecode 12:10:85def5fa, in python [14382]
[ 1470.612925] i915 0000:03:00.0: [drm] python[14382] context reset due to GPU hang
```

and vLLM crashes with `UR_RESULT_ERROR_DEVICE_LOST`

Is this a driver problem? Should a second A770 connected as m2 eGPU work or is this unsupported?

**How to reproduce**
Tough - you need my exotic setup

**Environment information**
```
❯ sudo bash env-check.sh 
-----------------------------------------------------------------
PYTHON_VERSION=3.13.3
-----------------------------------------------------------------
Transformers is not installed. 
-----------------------------------------------------------------
PyTorch is not installed. 
-----------------------------------------------------------------
ipex-llm WARNING: Package(s) not found: ipex-llm
-----------------------------------------------------------------
IPEX is not installed. 
-----------------------------------------------------------------
CPU Information: 
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               12
On-line CPU(s) list:                  0-11
Vendor ID:                            GenuineIntel
BIOS Vendor ID:                       Intel(R) Corporation
Model name:                           12th Gen Intel(R) Core(TM) i5-12500
BIOS Model name:                      12th Gen Intel(R) Core(TM) i5-12500 To Be Filled By O.E.M. CPU @ 4.0GHz
BIOS CPU family:                      205
CPU family:                           6
Model:                                151
Thread(s) per core:                   2
Core(s) per socket:                   6
Socket(s):                            1
Stepping:                             5
-----------------------------------------------------------------
Total CPU Memory: 45.6102 GB
Memory Type: DDR5 
-----------------------------------------------------------------
Operating System: 
Ubuntu 25.04 \n \l

-----------------------------------------------------------------
Linux ailab 6.11.0-25-generic #25-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 11 23:29:18 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------
CLI:
    Version: 1.2.39.20241101
    Build ID: 00000000

Service:
    Version: 1.2.39.20241101
    Build ID: 00000000
    Level Zero Version: 1.20.2
-----------------------------------------------------------------
  Driver UUID                                     32352e30-392e-3332-3936-310000000000
  Driver Version                                  25.09.32961
  Driver UUID                                     32352e30-392e-3332-3936-310000000000
  Driver Version                                  25.09.32961
  Driver UUID                                     32352e30-392e-3332-3936-310000000000
  Driver Version                                  25.09.32961
-----------------------------------------------------------------
Driver related package version:
rc  intel-fw-gpu                                   2024.24.5-337~22.04                        all          Firmware package for Intel integrated and discrete GPUs
ii  intel-level-zero-gpu-raytracing                1.0.0-0ubuntu1~24.10~ppa4                  amd64        Level Zero Ray Tracing Support library
-----------------------------------------------------------------
env-check.sh: line 167: sycl-ls: command not found
igpu not detected
-----------------------------------------------------------------
xpu-smi is properly installed. 
-----------------------------------------------------------------
+-----------+--------------------------------------------------------------------------------------+
| Device ID | Device Information                                                                   |
+-----------+--------------------------------------------------------------------------------------+
| 0         | Device Name: Intel(R) Arc(TM) A770 Graphics                                          |
|           | Vendor Name: Intel(R) Corporation                                                    |
|           | SOC UUID: 00000000-0000-0003-0000-000856a08086                                       |
|           | PCI BDF Address: 0000:03:00.0                                                        |
|           | DRM Device: /dev/dri/card1                                                           |
|           | Function Type: physical                                                              |
+-----------+--------------------------------------------------------------------------------------+
| 1         | Device Name: Intel(R) Arc(TM) A770 Graphics                                          |
|           | Vendor Name: Intel(R) Corporation                                                    |
|           | SOC UUID: 00000000-0000-0007-0000-000856a08086                                       |
|           | PCI BDF Address: 0000:07:00.0                                                        |
|           | DRM Device: /dev/dri/card0                                                           |
|           | Function Type: physical                                                              |
+-----------+--------------------------------------------------------------------------------------+
GPU0 Memory size=16G
GPU1 Memory size=16G
GPU2 Memory size=16G
-----------------------------------------------------------------
03:00.0 VGA compatible controller: Intel Corporation DG2 [Arc A770] (rev 08) (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation Device 1020
        Flags: bus master, fast devsel, latency 0, IRQ 188, IOMMU group 19
        Memory at 73000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 5000000000 (64-bit, prefetchable) [size=16G]
        Expansion ROM at 74000000 [disabled] [size=2M]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Endpoint, IntMsgNum 0
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
--
07:00.0 VGA compatible controller: Intel Corporation DG2 [Arc A770] (rev 08) (prog-if 00 [VGA controller])
        Subsystem: Device 172f:3937
        Flags: bus master, fast devsel, latency 0, IRQ 192, IOMMU group 24
        Memory at 71000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 4800000000 (64-bit, prefetchable) [size=16G]
        Expansion ROM at 72000000 [disabled] [size=2M]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Endpoint, IntMsgNum 0
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
--
7a:00.0 VGA compatible controller: Intel Corporation Battlemage G21 [Arc B580] (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation Device 1100
        Flags: bus master, fast devsel, latency 0, IRQ 196, IOMMU group 39
        Memory at 6f000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 4000000000 (64-bit, prefetchable) [size=16G]
        Expansion ROM at 70000000 [disabled] [size=2M]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Endpoint, IntMsgNum 0
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
-----------------------------------------------------------------
```

**Comment by HumerousGorgon** [comment]
vLLM freaks out if used with tensor parallel in any of the newer docker images past b12. I also had this problem. To be honest, I ended up testing out the llama.cpp portable build from the 2.3.0-nightly and it blew my socks off. Qwen3-30B-A3B-Q4 gguf from unSloth was running at 45 tokens per second on smaller context queries and at 30 tokens per second at larger ones. That's with the model + context spread across 3 GPUs but you could easily run it on 2 given the size it takes.
Trying to raise context above 22528 does result in an error, but I've lodged it as a bug.

**Comment by HumerousGorgon** [comment]
I've been running it bare metal and it's been going well. I did look at getting it working in a container but was getting shaderdumps all over the place.
One thing I will say is that the nightly releases are kinda slow to release to github, so I'm working on a docker image with the right stuff installed to compile the modules myself.

**Comment by gc-fu** [comment]
Hi, I wonder if you have installed the Intel out-of-tree driver?

https://dgpu-docs.intel.com/driver/kernel-driver-types.html#out-of-tree-drivers


Also, can you post your start script for vLLM service?  I saw you have set some environment varibles.

**Comment by fradav** [comment]
> Hm interesting. In an older issue I saw the recommendation to uncomment
> 
> ```
> #source /opt/intel/1ccl-wks/setvars.sh
> ```
> 
> and now it works.
> 
> ![Image](https://github.com/user-attachments/assets/cd370078-9c38-41a6-b545-46b235447815)
> 
> Pretty low CPU utilization but I'd guess that's a bottleneck from the Gen3 x4 interface of the 2nd Arc.

I wouldn’t incriminate the bus speed so fast, it seems that there are specific optimizations to the Qwen3 MOE arch to be done, like the ones there was added to llama.cpp. Someone correct me if I’m wrong, but my guess is that only one "expert" is activated on each card instead of the intended eight, so it is why it is so slow. On real supported backend, this thing is astonishingly fast.

**Comment by gc-fu** [comment]
Hi, this problem is caused by incompatible usage between our optimized oneCCL and CPU platform.

We will later release a new version that will fix this problem.

Currently, you can try image: `intelanalytics/ipex-llm-serving-xpu:b12-usm` or comment out the `source /opt/intel/1ccl-wks/setvars.sh`

**Comment by savvadesogle** [comment]
> We will later release a new version that will fix this problem

Hello. What version of "ipex-llm-serving-xpu" is currently suitable (the best) for Xeon v3/v4 and Arc A770 x4?

**Comment by gc-fu** [comment]
Please try set `export CCL_DG2_USM=1`
