### ISSUE TITLE
Loading GGUF model failed

### ISSUE THREAD

**Issue by kyang-06** [intel/ipex-llm#13208]
**Describe the bug**
When following [README](https://github.com/intel/ipex-llm/tree/main/python/llm/example/GPU/HuggingFace/Advanced-Quantizations/GGUF) to run Llama-2-Q4_0.gguf model inference, an error raised:

![Image](https://github.com/user-attachments/assets/9e5ff4d7-d408-4b83-97ff-2d877d3d8f39)

I've tried ipex-llm 2.1.0 and 2.3.0-nightly, both raise this error

**How to reproduce**
Steps to reproduce the error:
1. Following the readme, run `python generate.py --model llama-2-7b-chat.Q4_0.gguf --prompt "What is AI?"`

**Screenshots**
If applicable, add screenshots to help explain the problem

**Environment information**
If possible, please attach the output of the environment check script, using:
- https://github.com/intel/ipex-llm/blob/main/python/llm/scripts/env-check.bat, or
- https://github.com/intel/ipex-llm/blob/main/python/llm/scripts/env-check.sh

```
-----------------------------------------------------------------
PYTHON_VERSION=3.9.0
-----------------------------------------------------------------
transformers=4.36.0
-----------------------------------------------------------------
torch=2.1.0a0+cxx11.abi
-----------------------------------------------------------------
ipex-llm Version: 2.1.0
-----------------------------------------------------------------
ipex=2.1.10+xpu
-----------------------------------------------------------------
CPU Information: 
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        39 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               32
On-line CPU(s) list:                  0-31
Vendor ID:                            GenuineIntel
Model name:                           13th Gen Intel(R) Core(TM) i9-13900KF
CPU family:                           6
Model:                                183
Thread(s) per core:                   2
Core(s) per socket:                   24
Socket(s):                            1
Stepping:                             1
CPU max MHz:                          5800.0000
CPU min MHz:                          800.0000
BogoMIPS:                             5990.40
-----------------------------------------------------------------
Total CPU Memory: 94.1262 GB
-----------------------------------------------------------------
Operating System: 
Ubuntu 22.04.5 LTS \n \l

-----------------------------------------------------------------
Linux bjldempd1 6.8.0-51-generic #52~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Dec  9 15:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------
CLI:
    Version: 1.2.22.20231025
    Build ID: 00000000

Service:
    Version: 1.2.22.20231025
    Build ID: 00000000
    Level Zero Version: 1.15.5
-----------------------------------------------------------------
  Driver Version                                  2023.16.10.0.17_160000
  Driver Version                                  2023.16.10.0.17_160000
  Driver UUID                                     0f7477e2-3499-aea8-e286-b6eec4040fe4
  Driver Version                                  535.154.05
  Driver UUID                                     32342e33-352e-3330-3837-320000000000
  Driver Version                                  24.35.30872
-----------------------------------------------------------------
Driver related package version:
ii  intel-level-zero-gpu                             1.3.29735.27-914~22.04                  amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
ii  level-zero-dev                                   1.13.1-719~22.04                        amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
-----------------------------------------------------------------
igpu not detected
-----------------------------------------------------------------
xpu-smi is properly installed. 
-----------------------------------------------------------------
+-----------+--------------------------------------------------------------------------------------+
| Device ID | Device Information                                                                   |
+-----------+--------------------------------------------------------------------------------------+
| 0         | Device Name: Intel(R) Arc(TM) A770 Graphics                                          |
|           | Vendor Name: Intel(R) Corporation                                                    |
|           | SOC UUID: 00000000-0000-0003-0000-000856a08086                                       |
|           | PCI BDF Address: 0000:03:00.0                                                        |
|           | DRM Device: /dev/dri/card1                                                           |
|           | Function Type: physical                                                              |
+-----------+--------------------------------------------------------------------------------------+
GPU0 Memory size=16G
GPU1 Memory size=32G
-----------------------------------------------------------------
03:00.0 VGA compatible controller: Intel Corporation Device 56a0 (rev 08) (prog-if 00 [VGA controller])
	Subsystem: Device 1ef7:1997
	Flags: bus master, fast devsel, latency 0, IRQ 173, IOMMU group 16
	Memory at 80000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 4c00000000 (64-bit, prefetchable) [1;33m[size=16G][0m
	Expansion ROM at 81000000 [disabled] [size=2M]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915, xe
--
07:00.0 VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3090] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: Micro-Star International Co., Ltd. [MSI] GA102 [GeForce RTX 3090]
	Flags: bus master, fast devsel, latency 0, IRQ 196, IOMMU group 19
	Memory at 82000000 (32-bit, non-prefetchable) [size=16M]
	Memory at 4000000000 (64-bit, prefetchable) [1;33m[size=32G][0m
	Memory at 4800000000 (64-bit, prefetchable) [size=32M]
	I/O ports at 3000 [size=128]
	Expansion ROM at 83000000 [virtual] [disabled] [size=512K]
	Capabilities: <access denied>
-----------------------------------------------------------------
```

**Additional context**
Simply debugging shows that `model.model.layers[0].self_attn.q_proj` has wrong shape

![Image](https://github.com/user-attachments/assets/a035a367-1e31-4e56-b402-3c6232b03a3f)

**Comment by kyang-06** [comment]
Hi team. After deeply debugging, I found that the error is caused by unexpected shape of quantized linear weight. For example,   `self_attn.o_proj.weight` should have a shape of `(4096, 2176)` for `sym_int4` quantization, but got `(8912896,)`. 

[generate.py](https://github.com/intel/ipex-llm/blob/main/python/llm/example/GPU/HuggingFace/Advanced-Quantizations/GGUF/generate.py) invokes [load_gguf_model](https://github.com/intel/ipex-llm/blob/5a629ae470b524db8d0b0cfbb8dbd8bc906c6e8f/python/llm/src/ipex_llm/transformers/gguf/api.py#L31) -> [load_gguf_llama](https://github.com/intel/ipex-llm/blob/dd49368e0c617716d6993474f7fed95789ac35b5/python/llm/src/ipex_llm/transformers/gguf/models/llama.py#L29) -> [replace_with_low_bit_linear_for_module](https://github.com/intel/ipex-llm/blob/db5edba786136965d82e22ed4817e0599527e7b2/python/llm/src/ipex_llm/transformers/convert.py#L821-L827) -> [LowBitLinear ](https://github.com/intel/ipex-llm/blob/ac04992278271c3df291799fa2d52d282c7adcf1/python/llm/src/ipex_llm/transformers/low_bit_linear.py#L611-L614)-> [FP4Params](https://github.com/intel/ipex-llm/blob/ac04992278271c3df291799fa2d52d282c7adcf1/python/llm/src/ipex_llm/transformers/low_bit_linear.py#L332)

`FP4Params` triggers `quantization` method that quantizes the original weight and fake reshape weight shape, but `data.shape` still remains 1 dimension, which should be reshaped according to `qtype`. Please fix it.

**Comment by qiyuangong** [comment]
> Hi team. After deeply debugging, I found that the error is caused by unexpected shape of quantized linear weight. For example, `self_attn.o_proj.weight` should have a shape of `(4096, 2176)` for `sym_int4` quantization, but got `(8912896,)`.
> 
> [generate.py](https://github.com/intel/ipex-llm/blob/main/python/llm/example/GPU/HuggingFace/Advanced-Quantizations/GGUF/generate.py) invokes [load_gguf_model](https://github.com/intel/ipex-llm/blob/5a629ae470b524db8d0b0cfbb8dbd8bc906c6e8f/python/llm/src/ipex_llm/transformers/gguf/api.py#L31) -> [load_gguf_llama](https://github.com/intel/ipex-llm/blob/dd49368e0c617716d6993474f7fed95789ac35b5/python/llm/src/ipex_llm/transformers/gguf/models/llama.py#L29) -> [replace_with_low_bit_linear_for_module](https://github.com/intel/ipex-llm/blob/db5edba786136965d82e22ed4817e0599527e7b2/python/llm/src/ipex_llm/transformers/convert.py#L821-L827) -> [LowBitLinear ](https://github.com/intel/ipex-llm/blob/ac04992278271c3df291799fa2d52d282c7adcf1/python/llm/src/ipex_llm/transformers/low_bit_linear.py#L611-L614)-> [FP4Params](https://github.com/intel/ipex-llm/blob/ac04992278271c3df291799fa2d52d282c7adcf1/python/llm/src/ipex_llm/transformers/low_bit_linear.py#L332)
> 
> `FP4Params` triggers `quantization` method that quantizes the original weight, and then modifies `in_features` and `out_features`. But `data.shape` still remains at 1 dimension, which should be reshaped according to `qtype`. Please fix it.

Hi @kyang-06 

Thank you for the feedback and detailed debug! :)

`4096 * 2176 = 8912896`. Seems we don't correctly reshape the weight. We will review and address this issue.

**Comment by Uxito-Ada** [comment]
Hi @kyang-06 ,

Tks for your patience.

After days of breaking down, it is shown that the root cause is that [merge_linear](https://github.com/intel/ipex-llm/blob/main/python/llm/src/ipex_llm/transformers/models/common.py#L23) called by [merge_qkv_base](https://github.com/intel/ipex-llm/blob/main/python/llm/src/ipex_llm/transformers/models/common.py#L46) is unaware of GGUF format, which has already flatten weights to one-dimension vector. As a result, the linear cannot find the right in/out dimensions after merging GGUF's qkv.

As for suggestion, fortunately, GGUF's weights has already been quantized and flatten, therefore its qkv does not need to be merged. You can skip merge_qkv by modifing `generate.py`:

```python
# L48
model, tokenizer = AutoModelForCausalLM.from_gguf(model_path, optimize_model=False)
```

Then it goes smoothly in my env:

```bash
-------------------- Output --------------------
### HUMAN:
What is AI?

### RESPONSE:

AI is a term used to describe a type of computer software that is designed to perform tasks that typically require human intelligence, such as visual perception, speech
```

**Comment by kyang-06** [comment]
That's great! I have confirmed that it works.
